---

# an example playbook

- hosts: vault_instances
  strategy: linear
  become: true
  tasks:

    - name: verify vault_unseal_key exists if auto_unseal is not setup
      assert:
        that: vault_unseal_key is defined
      when: not auto_unseal

    - name: install secrets-gen
      import_role:
        name: vault_plugin_secret_gen

- hosts: vault_instances
  strategy: linear
  become: true
  serial: 1
  tasks:

    - import_role:
        name: vault_safe_restart

    - name: get shasum for plugin
      shell: "sha256sum {{ vault_plugin_config_path }}/vault-secrets-gen | cut -d ' ' -f1"
      register: sha
      changed_when: false # dont show changed when you get shasum

    - name: register plugin sha with vault
      command: "{{ vault_install_dir }}/vault write sys/plugins/catalog/secrets-gen sha_256={{ sha.stdout }} command='vault-secrets-gen'"
      environment:
        VAULT_ADDR: "{{ vault_addr }}"
        VAULT_TOKEN: "{{ vault_token }}"

    - name: enable vault plugin
      command: "{{ vault_install_dir }}/vault secrets enable -path='gen' -plugin-name='secrets-gen' plugin"
      environment:
        VAULT_ADDR: "{{ vault_addr }}"
        VAULT_TOKEN: "{{ vault_token }}"
      ignore_errors: true
